# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# (http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
# ===================================================================

spring:
  application:
    name: FashionGo TodoList
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 29801