# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# (http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
# ===================================================================

spring:
  application:
    name: FashionGo TodoList
  h2:
    console:
      enabled: true
server:
  port: 29801